-- +goose Up
-- Multi-tenant M1: tenants table + tenant_id on core identity tables.

CREATE TABLE IF NOT EXISTS tenants (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code varchar(64) NOT NULL,
  name varchar(128) NOT NULL,
  status smallint NOT NULL DEFAULT 1,
  plan varchar(64) NOT NULL DEFAULT 'free',
  max_users bigint NOT NULL DEFAULT 0,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tenants_code ON tenants (code);

INSERT INTO tenants (id, code, name, status, plan, max_users, created_at, updated_at)
VALUES (1, 'default', '默认租户', 1, 'free', 0, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- Ensure identity sequence continues after explicit id insert (PG).
SELECT setval(pg_get_serial_sequence('tenants', 'id'), GREATEST((SELECT MAX(id) FROM tenants), 1));

ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id bigint NOT NULL DEFAULT 1;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS tenant_id bigint NOT NULL DEFAULT 1;
ALTER TABLE departments ADD COLUMN IF NOT EXISTS tenant_id bigint NOT NULL DEFAULT 1;

UPDATE users SET tenant_id = 1 WHERE tenant_id IS NULL OR tenant_id = 0;
UPDATE roles SET tenant_id = 1 WHERE tenant_id IS NULL OR tenant_id = 0;
UPDATE departments SET tenant_id = 1 WHERE tenant_id IS NULL OR tenant_id = 0;

DROP INDEX IF EXISTS idx_users_username;
DROP INDEX IF EXISTS idx_users_email;
DROP INDEX IF EXISTS idx_users_phone;
DROP INDEX IF EXISTS idx_roles_code;
DROP INDEX IF EXISTS idx_departments_code;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_tenant_username ON users (tenant_id, username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_tenant_email ON users (tenant_id, email) WHERE email IS NOT NULL AND email <> '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_tenant_phone ON users (tenant_id, phone) WHERE phone IS NOT NULL AND phone <> '';
CREATE INDEX IF NOT EXISTS idx_users_tenant_id ON users (tenant_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_tenant_code ON roles (tenant_id, code);
CREATE INDEX IF NOT EXISTS idx_roles_tenant_id ON roles (tenant_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_departments_tenant_code ON departments (tenant_id, code);
CREATE INDEX IF NOT EXISTS idx_departments_tenant_id ON departments (tenant_id);

-- Permissions for tenant admin (platform catalog remains global).
INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at)
SELECT '租户列表', 'system:tenant:list', 2, '/api/v1/tenants', 'GET', 0, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = 'system:tenant:list');

INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at)
SELECT '租户详情', 'system:tenant:detail', 2, '/api/v1/tenants/:id', 'GET', 0, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = 'system:tenant:detail');

INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at)
SELECT '创建租户', 'system:tenant:create', 2, '/api/v1/tenants', 'POST', 0, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = 'system:tenant:create');

INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at)
SELECT '更新租户', 'system:tenant:update', 2, '/api/v1/tenants/:id', 'PUT', 0, NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = 'system:tenant:update');

-- Grant to super_admin role if present.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'super_admin'
  AND p.code IN ('system:tenant:list', 'system:tenant:detail', 'system:tenant:create', 'system:tenant:update')
  AND NOT EXISTS (
    SELECT 1 FROM role_permissions rp WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );

-- Optional menu entry under system.
INSERT INTO menus (name, title, icon, path, component, parent_id, sort, status, hidden, permission, created_at, updated_at)
SELECT 'Tenant', '租户管理', 'CloudServerOutlined', '/system/tenant', 'system/tenant', 
  COALESCE((SELECT id FROM menus WHERE path = '/system' LIMIT 1), 0),
  95, 1, 0, 'system:tenant:list', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM menus WHERE path = '/system/tenant');

-- +goose Down
DELETE FROM menus WHERE path = '/system/tenant';
DELETE FROM role_permissions WHERE permission_id IN (
  SELECT id FROM permissions WHERE code LIKE 'system:tenant:%'
);
DELETE FROM permissions WHERE code LIKE 'system:tenant:%';

DROP INDEX IF EXISTS idx_departments_tenant_code;
DROP INDEX IF EXISTS idx_departments_tenant_id;
DROP INDEX IF EXISTS idx_roles_tenant_code;
DROP INDEX IF EXISTS idx_roles_tenant_id;
DROP INDEX IF EXISTS idx_users_tenant_username;
DROP INDEX IF EXISTS idx_users_tenant_email;
DROP INDEX IF EXISTS idx_users_tenant_phone;
DROP INDEX IF EXISTS idx_users_tenant_id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_code ON roles (code);
CREATE UNIQUE INDEX IF NOT EXISTS idx_departments_code ON departments (code);

ALTER TABLE users DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE roles DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE departments DROP COLUMN IF EXISTS tenant_id;

DROP TABLE IF EXISTS tenants;
