-- +goose Up
-- 租户套餐（权限包）：套餐 = 可分配权限码集合；租户绑定套餐后，
-- 租户内（非平台超管）角色分配权限必须 ⊆ 套餐 permission_codes。
CREATE TABLE IF NOT EXISTS tenant_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(128) NOT NULL,
  permission_codes jsonb NOT NULL DEFAULT '[]',
  status smallint NOT NULL DEFAULT 1,
  remark varchar(255) NOT NULL DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_packages_name ON tenant_packages (name);

-- 租户绑定：NULL = 不限（未绑定套餐）。
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS package_id bigint DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_tenants_package_id ON tenants (package_id);

-- 租户套餐管理权限点（挂系统管理 parent_id=2）。超级管理员自动获得全部权限。
INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at) VALUES
('租户套餐查看', 'system:tenant-package:list', 2, '/api/v1/tenant-packages', 'GET', 2, NOW(), NOW()),
('租户套餐新建', 'system:tenant-package:create', 2, '/api/v1/tenant-packages', 'POST', 2, NOW(), NOW()),
('租户套餐更新', 'system:tenant-package:update', 2, '/api/v1/tenant-packages/:id', 'PUT', 2, NOW(), NOW()),
('租户套餐删除', 'system:tenant-package:delete', 2, '/api/v1/tenant-packages/:id', 'DELETE', 2, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- 超管角色补挂新权限（与 000001 的全量挂载语义一致，照 000020 格式）
INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions WHERE code IN (
  'system:tenant-package:list', 'system:tenant-package:create', 'system:tenant-package:update', 'system:tenant-package:delete'
)
ON CONFLICT DO NOTHING;

-- +goose Down
DELETE FROM role_permissions WHERE permission_id IN
  (SELECT id FROM permissions WHERE code IN (
    'system:tenant-package:list', 'system:tenant-package:create', 'system:tenant-package:update', 'system:tenant-package:delete'
  ));
DELETE FROM permissions WHERE code IN (
  'system:tenant-package:list', 'system:tenant-package:create', 'system:tenant-package:update', 'system:tenant-package:delete'
);

DROP INDEX IF EXISTS idx_tenants_package_id;
ALTER TABLE tenants DROP COLUMN IF EXISTS package_id;

DROP INDEX IF EXISTS idx_tenant_packages_name;
DROP TABLE IF EXISTS tenant_packages;
