-- +goose Up
-- 统一任务中心 M2：逐次执行账本。高频 worker 仍用 ops_job_heartbeats
-- 记录活性；只有离散执行显式写本表，避免空轮询制造无界历史。
CREATE TABLE IF NOT EXISTS public.ops_task_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id varchar(64) NOT NULL,
  task_key varchar(100) NOT NULL,
  service varchar(50) NOT NULL,
  description varchar(255) NOT NULL DEFAULT '',
  source varchar(24) NOT NULL DEFAULT 'worker',
  trigger_type varchar(24) NOT NULL DEFAULT 'scheduled',
  status varchar(16) NOT NULL DEFAULT 'running',
  attempt integer NOT NULL DEFAULT 1,
  correlation_id varchar(96) NOT NULL DEFAULT '',
  started_at timestamptz(3) NOT NULL,
  finished_at timestamptz(3),
  duration_ms bigint NOT NULL DEFAULT 0,
  message text NOT NULL DEFAULT '',
  error_message text NOT NULL DEFAULT '',
  created_at timestamptz(3) NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_ops_task_runs_run_id UNIQUE (run_id),
  CONSTRAINT ck_ops_task_runs_status CHECK (status IN ('running', 'succeeded', 'failed', 'cancelled')),
  CONSTRAINT ck_ops_task_runs_attempt CHECK (attempt > 0),
  CONSTRAINT ck_ops_task_runs_duration CHECK (duration_ms >= 0)
);
CREATE INDEX IF NOT EXISTS idx_ops_task_runs_started ON public.ops_task_runs (started_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_ops_task_runs_task ON public.ops_task_runs (task_key, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ops_task_runs_service_status ON public.ops_task_runs (service, status, started_at DESC);

-- 旧定时执行日志回填成统一历史；run_id 使用稳定前缀保证迁移可重复执行。
INSERT INTO public.ops_task_runs
  (run_id, task_key, service, description, source, trigger_type, status, attempt,
   started_at, finished_at, duration_ms, message, error_message, created_at)
SELECT
  'legacy-scheduled-' || l.id,
  'monitor.scheduled.' || l.job_id,
  'monitor-service',
  l.job_name,
  'scheduler',
  'legacy',
  CASE WHEN l.status = 1 THEN 'succeeded' ELSE 'failed' END,
  1,
  l.created_at - (GREATEST(l.duration, 0) * interval '1 millisecond'),
  l.created_at,
  GREATEST(l.duration, 0),
  CASE WHEN l.status = 1 THEN l.message ELSE '' END,
  CASE WHEN l.status = 0 THEN l.message ELSE '' END,
  l.created_at
FROM public.scheduled_job_logs l
ON CONFLICT (run_id) DO NOTHING;

-- 心跳只保留最后一轮，回填一条 snapshot 让升级后的总览立即可用；不伪造完整历史。
INSERT INTO public.ops_task_runs
  (run_id, task_key, service, description, source, trigger_type, status, attempt,
   started_at, finished_at, duration_ms, error_message, created_at)
SELECT
  'legacy-heartbeat-' || h.id,
  h.job_key,
  h.service,
  h.description,
  CASE WHEN h.service = 'ops-cron' THEN 'ops-cron' ELSE 'worker' END,
  'snapshot',
  CASE WHEN h.last_status = 'error' THEN 'failed' ELSE 'succeeded' END,
  1,
  h.last_run_at - (GREATEST(h.last_duration_ms, 0) * interval '1 millisecond'),
  h.last_run_at,
  GREATEST(h.last_duration_ms, 0),
  h.last_error,
  h.last_run_at
FROM public.ops_job_heartbeats h
ON CONFLICT (run_id) DO NOTHING;

UPDATE public.menus
SET title = '任务中心', updated_at = NOW()
WHERE path = '/monitor/job' AND title = '定时任务';

-- +goose Down
UPDATE public.menus
SET title = '定时任务', updated_at = NOW()
WHERE path = '/monitor/job' AND title = '任务中心';
DROP TABLE IF EXISTS public.ops_task_runs;
