-- +goose Up
-- OAuth2 授权服务端 M1（设计文档 docs/design/oauth2-server.md）：
-- 应用（客户端）注册 + 不透明令牌（存 SHA-256 哈希，防拖库）+ 用户授权记忆。
-- client_id 全局唯一（token 端点无租户上下文，按 client 定位租户）；其余查询按 tenant_id 隔离。

CREATE TABLE IF NOT EXISTS oauth2_clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  client_id varchar(64) NOT NULL,
  client_secret_hash varchar(255) NOT NULL DEFAULT '',
  name varchar(128) NOT NULL,
  logo varchar(255) NOT NULL DEFAULT '',
  description varchar(512) NOT NULL DEFAULT '',
  client_type smallint NOT NULL DEFAULT 1,
  redirect_uris jsonb NOT NULL DEFAULT '[]',
  scopes jsonb NOT NULL DEFAULT '[]',
  grant_types jsonb NOT NULL DEFAULT '[]',
  access_token_ttl integer NOT NULL DEFAULT 3600,
  refresh_token_ttl integer NOT NULL DEFAULT 2592000,
  auto_approve boolean NOT NULL DEFAULT false,
  status smallint NOT NULL DEFAULT 1,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);
COMMENT ON COLUMN oauth2_clients.client_type IS '1=机密客户端(服务端) 2=公开客户端(SPA/移动端,强制PKCE,无secret)';
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth2_clients_client_id ON oauth2_clients (client_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_clients_tenant_id ON oauth2_clients (tenant_id);

CREATE TABLE IF NOT EXISTS oauth2_access_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  token_hash varchar(64) NOT NULL,
  client_id varchar(64) NOT NULL,
  user_id bigint DEFAULT NULL,
  username varchar(128) NOT NULL DEFAULT '',
  scopes jsonb NOT NULL DEFAULT '[]',
  grant_type varchar(32) NOT NULL DEFAULT '',
  refresh_token_id bigint DEFAULT NULL,
  expires_at timestamptz(3) NOT NULL,
  revoked_at timestamptz(3) DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth2_access_tokens_hash ON oauth2_access_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_oauth2_access_tokens_client ON oauth2_access_tokens (client_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_access_tokens_user ON oauth2_access_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_access_tokens_refresh ON oauth2_access_tokens (refresh_token_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_access_tokens_expires ON oauth2_access_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_oauth2_access_tokens_tenant ON oauth2_access_tokens (tenant_id);

CREATE TABLE IF NOT EXISTS oauth2_refresh_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  token_hash varchar(64) NOT NULL,
  client_id varchar(64) NOT NULL,
  user_id bigint DEFAULT NULL,
  username varchar(128) NOT NULL DEFAULT '',
  scopes jsonb NOT NULL DEFAULT '[]',
  grant_type varchar(32) NOT NULL DEFAULT '',
  expires_at timestamptz(3) NOT NULL,
  revoked_at timestamptz(3) DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth2_refresh_tokens_hash ON oauth2_refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_oauth2_refresh_tokens_client ON oauth2_refresh_tokens (client_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_refresh_tokens_user ON oauth2_refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_refresh_tokens_expires ON oauth2_refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_oauth2_refresh_tokens_tenant ON oauth2_refresh_tokens (tenant_id);

CREATE TABLE IF NOT EXISTS oauth2_approvals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  user_id bigint NOT NULL,
  client_id varchar(64) NOT NULL,
  scopes jsonb NOT NULL DEFAULT '[]',
  expires_at timestamptz(3) NOT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth2_approvals_user_client ON oauth2_approvals (user_id, client_id);
CREATE INDEX IF NOT EXISTS idx_oauth2_approvals_tenant ON oauth2_approvals (tenant_id);

-- 权限点（照 000020 sms 范式，parent_id=2 系统管理）
INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at) VALUES
('OAuth2 应用查看', 'system:oauth2-client:list', 2, '/api/v1/oauth2/clients', 'GET', 2, NOW(), NOW()),
('OAuth2 应用新建', 'system:oauth2-client:create', 2, '/api/v1/oauth2/clients', 'POST', 2, NOW(), NOW()),
('OAuth2 应用更新', 'system:oauth2-client:update', 2, '/api/v1/oauth2/clients/:id', 'PUT', 2, NOW(), NOW()),
('OAuth2 应用删除', 'system:oauth2-client:delete', 2, '/api/v1/oauth2/clients/:id', 'DELETE', 2, NOW(), NOW()),
('OAuth2 重置密钥', 'system:oauth2-client:reset-secret', 2, '/api/v1/oauth2/clients/:id/reset-secret', 'POST', 2, NOW(), NOW()),
('OAuth2 令牌查看', 'system:oauth2-token:list', 2, '/api/v1/oauth2/tokens', 'GET', 2, NOW(), NOW()),
('OAuth2 令牌吊销', 'system:oauth2-token:delete', 2, '/api/v1/oauth2/tokens/:id', 'DELETE', 2, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- 超管角色补挂（按 code 定位，照 000012 范式）
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'super_admin'
  AND p.code LIKE 'system:oauth2-%'
  AND NOT EXISTS (
    SELECT 1 FROM role_permissions rp WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );

-- 菜单（无显式 id，照 000012 WHERE NOT EXISTS 模式）
INSERT INTO menus (name, title, icon, path, component, parent_id, sort, status, hidden, permission, created_at, updated_at)
SELECT 'OAuth2App', 'OAuth2 应用', 'ApiOutlined', '/system/oauth2', 'system/oauth2',
  COALESCE((SELECT id FROM menus WHERE path = '/system' LIMIT 1), 0),
  96, 1, 0, 'system:oauth2-client:list', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM menus WHERE path = '/system/oauth2');

-- +goose Down
DELETE FROM menus WHERE path = '/system/oauth2';
DELETE FROM role_permissions WHERE permission_id IN (
  SELECT id FROM permissions WHERE code LIKE 'system:oauth2-%'
);
DELETE FROM permissions WHERE code LIKE 'system:oauth2-%';

DROP TABLE IF EXISTS oauth2_approvals;
DROP TABLE IF EXISTS oauth2_refresh_tokens;
DROP TABLE IF EXISTS oauth2_access_tokens;
DROP TABLE IF EXISTS oauth2_clients;
