-- +goose Up
CREATE TABLE IF NOT EXISTS departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(100) NOT NULL,
  code varchar(50) DEFAULT NULL,
  parent_id bigint NOT NULL DEFAULT 0,
  leader varchar(50) DEFAULT '',
  phone varchar(20) DEFAULT '',
  email varchar(100) DEFAULT '',
  sort bigint NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_departments_code ON departments (code);
CREATE INDEX IF NOT EXISTS idx_departments_parent_id ON departments (parent_id);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username varchar(50) NOT NULL,
  password varchar(255) NOT NULL,
  nickname varchar(50) DEFAULT '',
  email varchar(100) DEFAULT NULL,
  phone varchar(20) DEFAULT NULL,
  avatar varchar(255) DEFAULT '',
  department_id bigint NOT NULL DEFAULT 0,
  must_change_password boolean NOT NULL DEFAULT false,
  status smallint NOT NULL DEFAULT 1,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_department_id ON users (department_id);

CREATE TABLE IF NOT EXISTS roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(50) NOT NULL,
  code varchar(50) NOT NULL,
  description varchar(255) DEFAULT '',
  data_scope varchar(32) NOT NULL DEFAULT 'self',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_code ON roles (code);
CREATE INDEX IF NOT EXISTS idx_roles_data_scope ON roles (data_scope);

CREATE TABLE IF NOT EXISTS permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(50) NOT NULL,
  code varchar(100) NOT NULL,
  type smallint NOT NULL,
  path varchar(255) DEFAULT '',
  method varchar(10) DEFAULT '',
  parent_id bigint NOT NULL DEFAULT 0,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_permissions_code ON permissions (code);
CREATE INDEX IF NOT EXISTS idx_permissions_parent_id ON permissions (parent_id);

CREATE TABLE IF NOT EXISTS menus (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(50) NOT NULL,
  title varchar(50) NOT NULL,
  icon varchar(100) DEFAULT '',
  path varchar(255) DEFAULT '',
  component varchar(255) DEFAULT '',
  parent_id bigint NOT NULL DEFAULT 0,
  sort bigint NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  hidden smallint NOT NULL DEFAULT 0,
  permission varchar(100) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_menus_parent_id ON menus (parent_id);

CREATE TABLE IF NOT EXISTS user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NOT NULL,
  role_id bigint NOT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_roles_user_role ON user_roles (user_id, role_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles (role_id);

CREATE TABLE IF NOT EXISTS role_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role_id bigint NOT NULL,
  permission_id bigint NOT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_role_permissions_role_permission ON role_permissions (role_id, permission_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON role_permissions (permission_id);

CREATE TABLE IF NOT EXISTS role_data_scope_departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  role_id bigint NOT NULL,
  department_id bigint NOT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_role_data_scope_department ON role_data_scope_departments (role_id, department_id);
CREATE INDEX IF NOT EXISTS idx_role_data_scope_departments_department_id ON role_data_scope_departments (department_id);

CREATE TABLE IF NOT EXISTS menu_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  menu_id bigint NOT NULL,
  permission_id bigint NOT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_menu_permissions_menu_permission ON menu_permissions (menu_id, permission_id);
CREATE INDEX IF NOT EXISTS idx_menu_permissions_permission_id ON menu_permissions (permission_id);

CREATE TABLE IF NOT EXISTS operation_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint DEFAULT NULL,
  username varchar(50) DEFAULT '',
  actor_type varchar(64) DEFAULT 'operator',
  actor_id varchar(128) DEFAULT 'web-console',
  request_id varchar(64) DEFAULT '',
  module varchar(50) DEFAULT '',
  action varchar(50) DEFAULT '',
  method varchar(10) DEFAULT '',
  path varchar(255) DEFAULT '',
  query varchar(1024) DEFAULT '',
  request_body text,
  response_body text,
  status bigint DEFAULT 0,
  ip varchar(45) DEFAULT '',
  user_agent varchar(500) DEFAULT '',
  latency bigint DEFAULT 0,
  error_msg varchar(1024) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_operation_logs_created_at ON operation_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_operation_logs_user_id ON operation_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_operation_logs_actor_type ON operation_logs (actor_type);
CREATE INDEX IF NOT EXISTS idx_operation_logs_actor_id ON operation_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_operation_logs_request_id ON operation_logs (request_id);

CREATE TABLE IF NOT EXISTS wm_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  actor_type varchar(64) DEFAULT 'operator',
  actor_id varchar(128) DEFAULT 'web-console',
  action varchar(128) NOT NULL,
  target_type varchar(64) NOT NULL,
  target_id varchar(128) NOT NULL,
  before_json jsonb DEFAULT NULL,
  after_json jsonb DEFAULT NULL,
  summary text,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_wm_audit_log_created_at ON wm_audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_wm_audit_log_actor_type ON wm_audit_log (actor_type);
CREATE INDEX IF NOT EXISTS idx_wm_audit_log_actor_id ON wm_audit_log (actor_id);
CREATE INDEX IF NOT EXISTS idx_wm_audit_log_action ON wm_audit_log (action);
CREATE INDEX IF NOT EXISTS idx_wm_audit_log_target_type ON wm_audit_log (target_type);
CREATE INDEX IF NOT EXISTS idx_wm_audit_log_target_id ON wm_audit_log (target_id);

CREATE TABLE IF NOT EXISTS files (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint DEFAULT NULL,
  file_name varchar(255) NOT NULL,
  file_path varchar(500) NOT NULL,
  file_size bigint NOT NULL DEFAULT 0,
  file_type varchar(50) DEFAULT '',
  mime_type varchar(100) DEFAULT '',
  extension varchar(20) DEFAULT '',
  storage_type varchar(20) DEFAULT 'local',
  url varchar(500) DEFAULT '',
  hash varchar(64) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_files_user_id ON files (user_id);
CREATE INDEX IF NOT EXISTS idx_files_hash ON files (hash);

CREATE TABLE IF NOT EXISTS login_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint DEFAULT NULL,
  username varchar(50) DEFAULT '',
  login_type smallint DEFAULT 1,
  status smallint DEFAULT 1,
  ip varchar(45) DEFAULT '',
  location varchar(100) DEFAULT '',
  device varchar(100) DEFAULT '',
  os varchar(50) DEFAULT '',
  browser varchar(100) DEFAULT '',
  user_agent varchar(500) DEFAULT '',
  message varchar(255) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_login_logs_created_at ON login_logs (created_at);
CREATE INDEX IF NOT EXISTS idx_login_logs_user_id ON login_logs (user_id);

CREATE TABLE IF NOT EXISTS dict_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(100) NOT NULL,
  code varchar(100) NOT NULL,
  description varchar(255) DEFAULT '',
  status smallint DEFAULT 1,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_dict_types_code ON dict_types (code);

CREATE TABLE IF NOT EXISTS dict_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  dict_type_id bigint NOT NULL,
  label varchar(100) NOT NULL,
  value varchar(100) NOT NULL,
  sort bigint DEFAULT 0,
  status smallint DEFAULT 1,
  remark varchar(255) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_dict_items_dict_type_id ON dict_items (dict_type_id);

CREATE TABLE IF NOT EXISTS oauth_bindings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NOT NULL,
  provider varchar(50) NOT NULL,
  provider_user_id varchar(100) NOT NULL,
  access_token varchar(255) DEFAULT '',
  refresh_token varchar(255) DEFAULT '',
  expires_at timestamptz(3) DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_oauth_bindings_user_id ON oauth_bindings (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_oauth_bindings_provider_user ON oauth_bindings (provider, provider_user_id);

CREATE TABLE IF NOT EXISTS scheduled_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name varchar(100) NOT NULL,
  group_name varchar(50) DEFAULT 'default',
  cron_expression varchar(50) NOT NULL,
  invoke_target varchar(255) NOT NULL,
  description varchar(500) DEFAULT '',
  status smallint DEFAULT 1,
  concurrent smallint DEFAULT 0,
  last_run_time timestamptz(3) DEFAULT NULL,
  next_run_time timestamptz(3) DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_scheduled_jobs_name ON scheduled_jobs (name);

CREATE TABLE IF NOT EXISTS scheduled_job_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  job_id bigint NOT NULL,
  job_name varchar(100) NOT NULL,
  status smallint DEFAULT 1,
  message text,
  duration bigint DEFAULT 0,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_scheduled_job_logs_job_id ON scheduled_job_logs (job_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_job_logs_created_at ON scheduled_job_logs (created_at);

CREATE TABLE IF NOT EXISTS notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(200) NOT NULL,
  content text NOT NULL,
  type smallint DEFAULT 1,
  status smallint DEFAULT 1,
  creator_id bigint DEFAULT NULL,
  creator varchar(50) DEFAULT '',
  start_time timestamptz(3) DEFAULT NULL,
  end_time timestamptz(3) DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_notices_creator_id ON notices (creator_id);

CREATE TABLE IF NOT EXISTS wm_console_route (
  route_key varchar(64) NOT NULL,
  path varchar(255) NOT NULL,
  name varchar(128) NOT NULL,
  component_key varchar(128) NOT NULL,
  redirect varchar(255) DEFAULT '',
  parent_key varchar(64) DEFAULT '',
  sort_order bigint DEFAULT 1000,
  hidden boolean DEFAULT false,
  public boolean DEFAULT false,
  enabled boolean DEFAULT true,
  permissions_json jsonb DEFAULT NULL,
  roles_json jsonb DEFAULT NULL,
  meta_json jsonb DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (route_key)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_wm_console_route_path ON wm_console_route (path);
CREATE UNIQUE INDEX IF NOT EXISTS idx_wm_console_route_name ON wm_console_route (name);
CREATE INDEX IF NOT EXISTS idx_wm_console_route_sort_order ON wm_console_route (sort_order);
CREATE INDEX IF NOT EXISTS idx_wm_console_route_parent_key ON wm_console_route (parent_key);
CREATE INDEX IF NOT EXISTS idx_wm_console_route_enabled ON wm_console_route (enabled);

CREATE TABLE IF NOT EXISTS wm_console_session (
  session_id varchar(64) NOT NULL,
  username varchar(128) NOT NULL,
  issued_at timestamptz(3) NOT NULL,
  expires_at timestamptz(3) NOT NULL,
  revoked_at timestamptz(3) DEFAULT NULL,
  last_seen_at timestamptz(3) DEFAULT NULL,
  client_ip_hash varchar(64) DEFAULT '',
  user_agent_hash varchar(64) DEFAULT '',
  user_agent_preview varchar(255) DEFAULT '',
  created_at timestamptz(3) NOT NULL,
  PRIMARY KEY (session_id)
);

CREATE INDEX IF NOT EXISTS idx_wm_console_session_username ON wm_console_session (username);
CREATE INDEX IF NOT EXISTS idx_wm_console_session_issued_at ON wm_console_session (issued_at);
CREATE INDEX IF NOT EXISTS idx_wm_console_session_expires_at ON wm_console_session (expires_at);
CREATE INDEX IF NOT EXISTS idx_wm_console_session_revoked_at ON wm_console_session (revoked_at);

CREATE TABLE IF NOT EXISTS wm_system_setting (
  setting_key varchar(128) NOT NULL,
  value_json jsonb DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (setting_key)
);

CREATE INDEX IF NOT EXISTS idx_wm_system_setting_updated_at ON wm_system_setting (updated_at);

CREATE TABLE IF NOT EXISTS schema_migrations (
  version varchar(255) NOT NULL,
  checksum varchar(64) DEFAULT '',
  applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (version)
);

INSERT INTO departments (id,name,code,parent_id,leader,sort,status,created_at,updated_at) VALUES
(1,'Headquarters','HQ',0,'admin',1,1,NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO users (id,username,password,nickname,email,phone,avatar,department_id,must_change_password,status,created_at,updated_at) VALUES
(1,'admin','$2a$10$x.kr72XCSvMcgkM0etydcOLlVPxYcjR8bK4sRYdf0VQmMxz8LskBe','管理员','admin@example.com',NULL,'',1,false,1,NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO roles (id,name,code,description,data_scope,created_at,updated_at) VALUES
(1,'超级管理员','super_admin','全部系统权限','all',NOW(),NOW()),
(2,'管理员','admin','系统管理员','department_and_children',NOW(),NOW()),
(3,'普通用户','user','标准用户权限','self',NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO permissions (id,name,code,type,path,method,parent_id,created_at,updated_at) VALUES
(1,'仪表盘','dashboard.view',1,'/dashboard','GET',0,NOW(),NOW()),
(2,'系统管理','system',1,'/system','',0,NOW(),NOW()),
(3,'用户列表','system:user:list',2,'/api/v1/users','GET',2,NOW(),NOW()),
(4,'用户详情','system:user:detail',2,'/api/v1/users/:id','GET',2,NOW(),NOW()),
(5,'创建用户','system:user:create',2,'/api/v1/users','POST',2,NOW(),NOW()),
(6,'更新用户','system:user:update',2,'/api/v1/users/:id','PUT',2,NOW(),NOW()),
(7,'删除用户','system:user:delete',2,'/api/v1/users/:id','DELETE',2,NOW(),NOW()),
(8,'角色列表','system:role:list',2,'/api/v1/roles','GET',2,NOW(),NOW()),
(9,'创建角色','system:role:create',2,'/api/v1/roles','POST',2,NOW(),NOW()),
(10,'更新角色','system:role:update',2,'/api/v1/roles/:id','PUT',2,NOW(),NOW()),
(11,'删除角色','system:role:delete',2,'/api/v1/roles/:id','DELETE',2,NOW(),NOW()),
(12,'权限列表','system:permission:list',2,'/api/v1/permissions','GET',2,NOW(),NOW()),
(13,'创建权限','system:permission:create',2,'/api/v1/permissions','POST',2,NOW(),NOW()),
(14,'更新权限','system:permission:update',2,'/api/v1/permissions/:id','PUT',2,NOW(),NOW()),
(15,'删除权限','system:permission:delete',2,'/api/v1/permissions/:id','DELETE',2,NOW(),NOW()),
(16,'菜单列表','system:menu:list',2,'/api/v1/menus','GET',2,NOW(),NOW()),
(17,'创建菜单','system:menu:create',2,'/api/v1/menus','POST',2,NOW(),NOW()),
(18,'更新菜单','system:menu:update',2,'/api/v1/menus/:id','PUT',2,NOW(),NOW()),
(19,'删除菜单','system:menu:delete',2,'/api/v1/menus/:id','DELETE',2,NOW(),NOW()),
(20,'部门列表','system:department:list',2,'/api/v1/departments','GET',2,NOW(),NOW()),
(21,'创建部门','system:department:create',2,'/api/v1/departments','POST',2,NOW(),NOW()),
(22,'更新部门','system:department:update',2,'/api/v1/departments/:id','PUT',2,NOW(),NOW()),
(23,'删除部门','system:department:delete',2,'/api/v1/departments/:id','DELETE',2,NOW(),NOW()),
(24,'操作日志','system:log:operation',2,'/api/v1/operation-logs','GET',2,NOW(),NOW()),
(25,'审计日志','system:log:audit',2,'/api/v1/logs/audit','GET',2,NOW(),NOW()),
(26,'登录日志','system:log:login',2,'/api/v1/login-logs','GET',2,NOW(),NOW()),
(27,'在线用户','system:online-user:list',2,'/api/v1/online-users','GET',2,NOW(),NOW()),
(28,'强制下线','system:online-user:kick',2,'/api/v1/online-users/:token_id','DELETE',2,NOW(),NOW()),
(29,'通知公告','system:notice:list',2,'/api/v1/notices','GET',2,NOW(),NOW()),
(30,'创建公告','system:notice:create',2,'/api/v1/notices','POST',2,NOW(),NOW()),
(31,'更新公告','system:notice:update',2,'/api/v1/notices/:id','PUT',2,NOW(),NOW()),
(32,'删除公告','system:notice:delete',2,'/api/v1/notices/:id','DELETE',2,NOW(),NOW()),
(33,'文件列表','system:file:list',2,'/api/v1/files','GET',2,NOW(),NOW()),
(34,'上传文件','system:file:upload',2,'/api/v1/files/upload','POST',2,NOW(),NOW()),
(35,'删除文件','system:file:delete',2,'/api/v1/files/:id','DELETE',2,NOW(),NOW()),
(36,'字典列表','system:dict:list',2,'/api/v1/dict-types','GET',2,NOW(),NOW()),
(37,'创建字典','system:dict:create',2,'/api/v1/dict-types','POST',2,NOW(),NOW()),
(38,'更新字典','system:dict:update',2,'/api/v1/dict-types/:id','PUT',2,NOW(),NOW()),
(39,'删除字典','system:dict:delete',2,'/api/v1/dict-types/:id','DELETE',2,NOW(),NOW()),
(40,'服务器监控','system:monitor:server',2,'/api/v1/monitor/server','GET',2,NOW(),NOW()),
(41,'数据库监控','system:monitor:mysql',2,'/api/v1/monitor/mysql','GET',2,NOW(),NOW()),
(42,'缓存监控','system:monitor:redis',2,'/api/v1/monitor/redis','GET',2,NOW(),NOW()),
(43,'定时任务','system:job:list',2,'/api/v1/monitor/jobs','GET',2,NOW(),NOW()),
(44,'创建任务','system:job:create',2,'/api/v1/monitor/jobs','POST',2,NOW(),NOW()),
(45,'更新任务','system:job:update',2,'/api/v1/monitor/jobs/:id','PUT',2,NOW(),NOW()),
(46,'删除任务','system:job:delete',2,'/api/v1/monitor/jobs/:id','DELETE',2,NOW(),NOW()),
(47,'执行任务','system:job:run',2,'/api/v1/monitor/jobs/:id/run','POST',2,NOW(),NOW()),
(48,'控制台设置读取','settings.read',2,'/api/v1/auth/routes','GET',2,NOW(),NOW()),
(49,'控制台设置写入','settings.write',2,'/api/v1/console-routes','POST',2,NOW(),NOW()),
(50,'权限治理读取','rbac.read',2,'/api/v1/users','GET',2,NOW(),NOW()),
(51,'权限治理写入','rbac.write',2,'/api/v1/users','POST',2,NOW(),NOW()),
(52,'日志读取','logs.read',2,'/api/v1/operation-logs','GET',2,NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO menus (id,name,title,icon,path,component,parent_id,sort,status,hidden,permission,created_at,updated_at) VALUES
(1,'dashboard','仪表盘','dashboard','/dashboard','Layout',0,0,1,0,'',NOW(),NOW()),
(2,'dashboard-index','系统概览','dashboard','/dashboard/index','dashboard/index',1,1,1,0,'dashboard.view',NOW(),NOW()),
(10,'system','系统管理','setting','/system','Layout',0,1,1,0,'',NOW(),NOW()),
(11,'user','用户管理','user','/system/user','system/user/index',10,1,1,0,'system:user:list',NOW(),NOW()),
(12,'role','角色管理','user-safety','/system/role','system/role/index',10,2,1,0,'system:role:list',NOW(),NOW()),
(13,'permission','权限管理','secured','/system/permission','system/permission/index',10,3,1,0,'system:permission:list',NOW(),NOW()),
(14,'menu','菜单管理','menu','/system/menu','system/menu/index',10,4,1,0,'system:menu:list',NOW(),NOW()),
(15,'department','部门管理','root-list','/system/department','system/department/index',10,5,1,0,'system:department:list',NOW(),NOW()),
(16,'file','文件管理','file','/system/file','system/file/index',10,6,1,0,'system:file:list',NOW(),NOW()),
(17,'dict','字典管理','data-base','/system/dict','system/dict/index',10,7,1,0,'system:dict:list',NOW(),NOW()),
(18,'notice','通知公告','notification','/system/notice','system/notice/index',10,8,1,0,'system:notice:list',NOW(),NOW()),
(19,'online-user','在线用户','user-list','/system/online-user','system/online-user/index',10,9,1,0,'system:online-user:list',NOW(),NOW()),
(20,'operation-log','操作日志','time','/system/operation-log','system/operation-log/index',10,10,1,0,'system:log:operation',NOW(),NOW()),
(21,'login-log','登录日志','time','/system/login-log','system/login-log/index',10,11,1,0,'system:log:login',NOW(),NOW()),
(30,'monitor','系统监控','chart-analytics','/monitor','Layout',0,2,1,0,'',NOW(),NOW()),
(31,'monitor-job','定时任务','time','/monitor/job','monitor/job/index',30,1,1,0,'system:job:list',NOW(),NOW()),
(32,'monitor-server','服务器监控','server','/monitor/server','monitor/server/index',30,2,1,0,'system:monitor:server',NOW(),NOW()),
(33,'monitor-mysql','数据库监控','data-base','/monitor/mysql','monitor/mysql/index',30,3,1,0,'system:monitor:mysql',NOW(),NOW()),
(34,'monitor-redis','缓存监控','data','/monitor/redis','monitor/redis/index',30,4,1,0,'system:monitor:redis',NOW(),NOW()),
(40,'profile','个人中心','user-circle','/profile','Layout',0,99,1,1,'',NOW(),NOW()),
(41,'profile-index','个人中心','user','/profile/index','profile/index',40,1,1,0,'',NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id,role_id) VALUES (1,1) ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id,permission_id) SELECT 1, id FROM permissions ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id,permission_id) SELECT 2, id FROM permissions WHERE code IN ('dashboard.view','system:user:list','system:role:list','system:permission:list','system:menu:list','system:department:list','system:log:operation','system:log:login','system:file:list','system:dict:list','system:notice:list','system:online-user:list','system:monitor:server','system:monitor:mysql','system:monitor:redis','system:job:list','settings.read','rbac.read','logs.read') ON CONFLICT DO NOTHING;

INSERT INTO menu_permissions (menu_id,permission_id)
SELECT m.id, p.id
FROM menus m
JOIN permissions p ON p.code = m.permission
WHERE m.permission <> ''
ON CONFLICT DO NOTHING;

INSERT INTO dict_types (id,name,code,description,status,created_at,updated_at) VALUES
(1,'用户状态','user_status','常用用户状态值',1,NOW(),NOW()),
(2,'公告类型','notice_type','通知公告类型值',1,NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO dict_items (dict_type_id,label,value,sort,status,remark,created_at,updated_at) VALUES
(1,'启用','1',1,1,'',NOW(),NOW()),
(1,'禁用','0',2,1,'',NOW(),NOW()),
(2,'通知','1',1,1,'',NOW(),NOW()),
(2,'公告','2',2,1,'',NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO notices (id,title,content,type,status,creator_id,creator,created_at,updated_at) VALUES
(1,'欢迎使用','后台管理系统数据库已准备就绪。',1,1,1,'admin',NOW(),NOW())
ON CONFLICT DO NOTHING;

INSERT INTO wm_console_route (route_key,path,name,component_key,sort_order,enabled,permissions_json,roles_json,meta_json,created_at,updated_at) VALUES
('dashboard','/dashboard','Dashboard','DashboardPage',100,true,'["dashboard.view"]','[]','{"title":"仪表盘","navTitle":"仪表盘","groupId":"monitor","icon":"SettingIcon","permissions":["dashboard.view"],"seedVersion":6}',NOW(),NOW()),
('rbac-users','/rbac/users','RbacUsers','RbacGovernancePage',210,true,'["rbac.read","logs.read"]','[]','{"title":"用户管理","navTitle":"用户管理","groupId":"rbac","icon":"SettingIcon","permissions":["rbac.read","logs.read"],"seedVersion":6}',NOW(),NOW()),
('rbac-roles','/rbac/roles','RbacRoles','RbacGovernancePage',220,true,'["rbac.read","logs.read"]','[]','{"title":"角色管理","navTitle":"角色管理","groupId":"rbac","icon":"SettingIcon","permissions":["rbac.read","logs.read"],"seedVersion":6}',NOW(),NOW()),
('rbac-policies','/rbac/policies','RbacPolicies','RbacGovernancePage',230,true,'["rbac.read","logs.read"]','[]','{"title":"权限管理","navTitle":"权限管理","groupId":"rbac","icon":"SettingIcon","permissions":["rbac.read","logs.read"],"seedVersion":6}',NOW(),NOW()),
('rbac-departments','/rbac/departments','RbacDepartments','RbacGovernancePage',240,true,'["rbac.read","logs.read"]','[]','{"title":"部门管理","navTitle":"部门管理","groupId":"rbac","icon":"SettingIcon","permissions":["rbac.read","logs.read"],"seedVersion":6}',NOW(),NOW()),
('audit','/audit','Audit','AuditPage',270,true,'["logs.read"]','[]','{"title":"审计日志","navTitle":"审计日志","groupId":"security","icon":"SettingIcon","permissions":["logs.read"],"seedVersion":6}',NOW(),NOW()),
('security-logins','/security/logins','SecurityLogins','SecurityLoginsPage',280,true,'["logs.read"]','[]','{"title":"登录日志","navTitle":"登录日志","groupId":"security","icon":"SettingIcon","permissions":["logs.read"],"seedVersion":6}',NOW(),NOW()),
('settings-routes','/settings/routes','ConsoleRoutes','ConsoleRoutesPage',315,true,'["settings.write"]','[]','{"title":"路由设置","navTitle":"路由设置","groupId":"settings","icon":"SettingIcon","permissions":["settings.write"],"seedVersion":6}',NOW(),NOW())
ON CONFLICT DO NOTHING;

-- Seed rows above insert explicit ids into identity columns; realign the
-- identity sequences so application-level inserts don't collide.
SELECT setval(pg_get_serial_sequence('departments','id'), (SELECT COALESCE(MAX(id),1) FROM departments));
SELECT setval(pg_get_serial_sequence('users','id'), (SELECT COALESCE(MAX(id),1) FROM users));
SELECT setval(pg_get_serial_sequence('roles','id'), (SELECT COALESCE(MAX(id),1) FROM roles));
SELECT setval(pg_get_serial_sequence('permissions','id'), (SELECT COALESCE(MAX(id),1) FROM permissions));
SELECT setval(pg_get_serial_sequence('menus','id'), (SELECT COALESCE(MAX(id),1) FROM menus));
SELECT setval(pg_get_serial_sequence('dict_types','id'), (SELECT COALESCE(MAX(id),1) FROM dict_types));
SELECT setval(pg_get_serial_sequence('notices','id'), (SELECT COALESCE(MAX(id),1) FROM notices));

-- +goose Down
DROP TABLE IF EXISTS schema_migrations;
DROP TABLE IF EXISTS wm_system_setting;
DROP TABLE IF EXISTS wm_console_session;
DROP TABLE IF EXISTS wm_console_route;
DROP TABLE IF EXISTS notices;
DROP TABLE IF EXISTS scheduled_job_logs;
DROP TABLE IF EXISTS scheduled_jobs;
DROP TABLE IF EXISTS oauth_bindings;
DROP TABLE IF EXISTS dict_items;
DROP TABLE IF EXISTS dict_types;
DROP TABLE IF EXISTS login_logs;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS wm_audit_log;
DROP TABLE IF EXISTS operation_logs;
DROP TABLE IF EXISTS menu_permissions;
DROP TABLE IF EXISTS role_data_scope_departments;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS menus;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS departments;
