-- +goose Up
ALTER TABLE users
  ADD COLUMN totp_secret varchar(255) NOT NULL DEFAULT '',
  ADD COLUMN totp_enabled boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS totp_recovery_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NOT NULL,
  code_hash varchar(255) NOT NULL,
  used_at timestamptz(3) DEFAULT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_totp_recovery_codes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_totp_recovery_codes_user_id ON totp_recovery_codes (user_id);
CREATE INDEX IF NOT EXISTS idx_totp_recovery_codes_user_unused ON totp_recovery_codes (user_id, used_at);

-- +goose Down
DROP TABLE IF EXISTS totp_recovery_codes;

ALTER TABLE users
  DROP COLUMN totp_enabled,
  DROP COLUMN totp_secret;
