-- +goose Up
-- 岗位管理（借鉴 ruoyi-vue-pro）：岗位实体 + 用户-岗位关联。
-- 岗位在租户内以 code 唯一；用户可挂多个岗位。
-- 表名带 sys_ 前缀：裸 "posts" 与社媒内容中台的 posts（内容库）撞名。

CREATE TABLE IF NOT EXISTS sys_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  code varchar(64) NOT NULL,
  name varchar(64) NOT NULL,
  sort bigint NOT NULL DEFAULT 0,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(500) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_posts_tenant_code ON sys_posts (tenant_id, code);
CREATE INDEX IF NOT EXISTS idx_sys_posts_tenant_id ON sys_posts (tenant_id);

CREATE TABLE IF NOT EXISTS sys_user_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NOT NULL,
  post_id bigint NOT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_sys_user_posts_user_post ON sys_user_posts (user_id, post_id);
CREATE INDEX IF NOT EXISTS idx_sys_user_posts_post_id ON sys_user_posts (post_id);

-- 岗位权限点（幂等）；菜单条目由 menu_seed.go 统一播种，此处不插菜单。
INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at) VALUES
('岗位列表', 'system:post:list', 2, '/api/v1/posts', 'GET', 2, NOW(), NOW()),
('创建岗位', 'system:post:create', 2, '/api/v1/posts', 'POST', 2, NOW(), NOW()),
('更新岗位', 'system:post:update', 2, '/api/v1/posts/:id', 'PUT', 2, NOW(), NOW()),
('删除岗位', 'system:post:delete', 2, '/api/v1/posts/:id', 'DELETE', 2, NOW(), NOW())
ON CONFLICT DO NOTHING;

-- 超管角色补挂新权限（与 000001 的全量挂载语义一致）
INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions WHERE code IN ('system:post:list', 'system:post:create', 'system:post:update', 'system:post:delete')
ON CONFLICT DO NOTHING;

-- +goose Down
DELETE FROM role_permissions WHERE permission_id IN
  (SELECT id FROM permissions WHERE code IN ('system:post:list', 'system:post:create', 'system:post:update', 'system:post:delete'));
DELETE FROM permissions WHERE code IN ('system:post:list', 'system:post:create', 'system:post:update', 'system:post:delete');

DROP TABLE IF EXISTS sys_user_posts;
DROP TABLE IF EXISTS sys_posts;
