-- +goose Up
-- 错误码管理（借鉴 ruoyi-vue-pro）：错误码 → 对外文案映射表。
-- 控制台在线改文案，各服务经 30s TTL 缓存读取，无需重启热生效。
-- code 与 shared/pkg/response 的 ErrorCode 常量对齐（如 DICT_TYPE_NOT_FOUND）。
CREATE TABLE IF NOT EXISTS error_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code varchar(128) NOT NULL,
  message varchar(512) NOT NULL,
  memo varchar(255) DEFAULT '',
  scope varchar(64) NOT NULL DEFAULT 'global',
  status smallint DEFAULT 1,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_error_codes_code ON error_codes (code);

-- 种子：system 服务现有常见错误文案（幂等，已存在则跳过）。
-- memo 记录代码里的默认英文文案，便于对照与回退。
INSERT INTO error_codes (code, message, memo, scope, status, created_at, updated_at) VALUES
('BAD_REQUEST', '请求参数有误，请检查后重试', '默认: bad request（通用参数校验失败）', 'global', 1, NOW(), NOW()),
('UNAUTHORIZED', '登录状态已失效，请重新登录', '默认: unauthorized（认证失败/令牌失效）', 'global', 1, NOW(), NOW()),
('FORBIDDEN', '权限不足，无法执行该操作', '默认: insufficient permissions（权限中间件拒绝）', 'global', 1, NOW(), NOW()),
('NOT_FOUND', '请求的资源不存在', '默认: not found（通用 404）', 'global', 1, NOW(), NOW()),
('INTERNAL_SERVER_ERROR', '系统繁忙，请稍后重试', '默认: internal server error（通用 500）', 'global', 1, NOW(), NOW()),
('DICT_TYPE_CODE_ALREADY_EXISTS', '字典编码已存在', '默认: dict type code already exists（system 字典模块）', 'system', 1, NOW(), NOW()),
('DICT_TYPE_NOT_FOUND', '字典类型不存在', '默认: dict type not found（system 字典模块，已接入覆盖示例）', 'system', 1, NOW(), NOW()),
('DICT_ITEM_NOT_FOUND', '字典项不存在', '默认: dict item not found（system 字典模块，已接入覆盖示例）', 'system', 1, NOW(), NOW()),
('NOTICE_NOT_FOUND', '公告不存在或已下线', '默认: notice not found（system 公告模块，已接入覆盖示例）', 'system', 1, NOW(), NOW()),
('MENU_NOT_FOUND', '菜单不存在', '默认: menu not found（system 菜单模块）', 'system', 1, NOW(), NOW())
ON CONFLICT (code) DO NOTHING;

-- 错误码管理权限点：超级管理员自动获得全部权限（与 000017 语义一致）。
INSERT INTO permissions (name, code, type, path, method, parent_id, created_at, updated_at) VALUES
('错误码查看', 'system:errcode:list', 2, '/api/v1/error-codes', 'GET', 2, NOW(), NOW()),
('错误码新增', 'system:errcode:create', 2, '/api/v1/error-codes', 'POST', 2, NOW(), NOW()),
('错误码修改', 'system:errcode:update', 2, '/api/v1/error-codes/:id', 'PUT', 2, NOW(), NOW()),
('错误码删除', 'system:errcode:delete', 2, '/api/v1/error-codes/:id', 'DELETE', 2, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions WHERE code IN ('system:errcode:list', 'system:errcode:create', 'system:errcode:update', 'system:errcode:delete')
ON CONFLICT DO NOTHING;

-- +goose Down
DELETE FROM role_permissions WHERE permission_id IN
  (SELECT id FROM permissions WHERE code IN ('system:errcode:list', 'system:errcode:create', 'system:errcode:update', 'system:errcode:delete'));
DELETE FROM permissions WHERE code IN ('system:errcode:list', 'system:errcode:create', 'system:errcode:update', 'system:errcode:delete');
DROP TABLE IF EXISTS error_codes;
