-- +goose Up
-- 短信管理三件套：渠道 / 模板 / 发送日志（借鉴 ruoyi-vue-pro 短信模块）。
-- 渠道 config 存 JSON（access_key / secret / sign_name 等），密钥只落库不进代码；
-- 模板 code 租户内唯一；日志记录渲染后内容与云厂商回执。
-- 权限与菜单种子由主会话统一接线，此迁移只建表。

CREATE TABLE IF NOT EXISTS sms_channels (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  name varchar(100) NOT NULL,
  provider varchar(32) NOT NULL,
  config json DEFAULT NULL,
  status smallint NOT NULL DEFAULT 1,
  remark varchar(255) NOT NULL DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_sms_channels_tenant_id ON sms_channels (tenant_id);

CREATE TABLE IF NOT EXISTS sms_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  code varchar(100) NOT NULL,
  name varchar(100) NOT NULL,
  channel_id bigint NOT NULL DEFAULT 0,
  content text NOT NULL DEFAULT '',
  type smallint NOT NULL DEFAULT 1,
  provider_template_id varchar(100) NOT NULL DEFAULT '',
  status smallint NOT NULL DEFAULT 1,
  remark varchar(255) NOT NULL DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_sms_templates_tenant_code ON sms_templates (tenant_id, code);
CREATE INDEX IF NOT EXISTS idx_sms_templates_channel_id ON sms_templates (channel_id);

CREATE TABLE IF NOT EXISTS sms_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL DEFAULT 1,
  mobile varchar(32) NOT NULL DEFAULT '',
  template_code varchar(100) NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  params json DEFAULT NULL,
  channel_id bigint NOT NULL DEFAULT 0,
  channel_name varchar(100) NOT NULL DEFAULT '',
  provider varchar(32) NOT NULL DEFAULT '',
  status varchar(16) NOT NULL DEFAULT 'sending',
  provider_msg_id varchar(128) NOT NULL DEFAULT '',
  error varchar(512) NOT NULL DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_sms_logs_tenant_id ON sms_logs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_sms_logs_mobile ON sms_logs (mobile);
CREATE INDEX IF NOT EXISTS idx_sms_logs_template_code ON sms_logs (template_code);
CREATE INDEX IF NOT EXISTS idx_sms_logs_status ON sms_logs (status);

-- +goose Down
DROP TABLE IF EXISTS sms_logs;
DROP TABLE IF EXISTS sms_templates;
DROP TABLE IF EXISTS sms_channels;
