-- +goose Up
-- 邀请注册：POST /register 从公开自注册改为邀请制。管理员发邀请链接，token 绑定
-- 租户 + 可选角色，单次使用（used_at 原子消费，复用 TOTP recovery-code 模式）。
CREATE TABLE IF NOT EXISTS invites (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tenant_id bigint NOT NULL,
  role_id bigint NULL,
  email varchar(255) NOT NULL DEFAULT '',
  token_hash char(64) NOT NULL,
  expires_at timestamptz(3) NOT NULL,
  used_at timestamptz(3) NULL,
  revoked_at timestamptz(3) NULL,
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz(3) NOT NULL DEFAULT NOW(),
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_invites_token_hash ON invites (token_hash);
CREATE INDEX IF NOT EXISTS idx_invites_tenant_id ON invites (tenant_id);

-- +goose Down
DROP TABLE IF EXISTS invites;
