-- +goose Up
-- 开放平台 Webhook：audit_logs 事实表 fanout → 持久化投递队列 → HMAC HTTP。
-- audit 独属表落 audit_svc；权限与菜单仍是 public 平台共享表。

CREATE TABLE IF NOT EXISTS audit_svc.webhook_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL DEFAULT 1,
  name varchar(128) NOT NULL,
  endpoint_url varchar(2048) NOT NULL,
  event_actions jsonb NOT NULL DEFAULT '[]',
  start_audit_log_id bigint NOT NULL DEFAULT 0,
  secret_hash varchar(64) NOT NULL,
  secret_ciphertext text NOT NULL DEFAULT '',
  status smallint NOT NULL DEFAULT 1,
  consecutive_failures integer NOT NULL DEFAULT 0,
  last_delivered_at timestamptz(3),
  last_error text NOT NULL DEFAULT '',
  created_by bigint NOT NULL DEFAULT 0,
  created_at timestamptz(3) NOT NULL DEFAULT NOW(),
  updated_at timestamptz(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_tenant ON audit_svc.webhook_subscriptions (tenant_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_active ON audit_svc.webhook_subscriptions (tenant_id, status) WHERE status = 1;
ALTER TABLE audit_svc.webhook_subscriptions
  DROP CONSTRAINT IF EXISTS ck_webhook_subscriptions_status;
ALTER TABLE audit_svc.webhook_subscriptions
  ADD CONSTRAINT ck_webhook_subscriptions_status CHECK (status IN (0, 1));

CREATE TABLE IF NOT EXISTS audit_svc.webhook_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL DEFAULT 1,
  subscription_id bigint NOT NULL,
  audit_log_id bigint NOT NULL,
  event_id varchar(96) NOT NULL,
  event_action varchar(128) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(24) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  response_status integer,
  response_body varchar(1024) NOT NULL DEFAULT '',
  last_error varchar(1024) NOT NULL DEFAULT '',
  next_attempt_at timestamptz(3) NOT NULL DEFAULT NOW(),
  delivered_at timestamptz(3),
  created_at timestamptz(3) NOT NULL DEFAULT NOW(),
  updated_at timestamptz(3) NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_webhook_delivery_event UNIQUE (subscription_id, audit_log_id)
);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_tenant ON audit_svc.webhook_deliveries (tenant_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_pending ON audit_svc.webhook_deliveries (status, next_attempt_at, id) WHERE status IN ('pending', 'retrying');
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_subscription ON audit_svc.webhook_deliveries (tenant_id, subscription_id, id DESC);
ALTER TABLE audit_svc.webhook_deliveries
  DROP CONSTRAINT IF EXISTS ck_webhook_deliveries_status;
ALTER TABLE audit_svc.webhook_deliveries
  ADD CONSTRAINT ck_webhook_deliveries_status CHECK (status IN ('pending', 'retrying', 'sent', 'failed'));

CREATE TABLE IF NOT EXISTS audit_svc.webhook_cursors (
  tenant_id bigint PRIMARY KEY,
  last_audit_log_id bigint NOT NULL DEFAULT 0,
  updated_at timestamptz(3) NOT NULL DEFAULT NOW()
);

INSERT INTO permissions (name, code, description, type, path, method, parent_id, created_at, updated_at) VALUES
('Webhook 订阅查看', 'system:webhook:list', '查看开放平台 Webhook 订阅与投递记录', 3, '/api/v1/webhooks', 'GET', 2, NOW(), NOW()),
('Webhook 订阅新建', 'system:webhook:create', '创建开放平台 Webhook 订阅', 3, '/api/v1/webhooks', 'POST', 2, NOW(), NOW()),
('Webhook 订阅更新', 'system:webhook:update', '更新或启停开放平台 Webhook 订阅', 3, '/api/v1/webhooks/:id', 'PUT', 2, NOW(), NOW()),
('Webhook 订阅删除', 'system:webhook:delete', '删除开放平台 Webhook 订阅', 3, '/api/v1/webhooks/:id', 'DELETE', 2, NOW(), NOW()),
('Webhook 密钥重置', 'system:webhook:reset-secret', '重置 Webhook HMAC 签名密钥', 3, '/api/v1/webhooks/:id/reset-secret', 'POST', 2, NOW(), NOW())
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.code = 'super_admin' AND p.code LIKE 'system:webhook:%'
  AND NOT EXISTS (SELECT 1 FROM role_permissions rp WHERE rp.role_id = r.id AND rp.permission_id = p.id);

INSERT INTO menus (name, title, icon, path, component, parent_id, sort, status, hidden, permission, created_at, updated_at)
SELECT 'webhooks', 'Webhook 订阅', 'api', '/system/webhooks', 'system/webhooks/index',
  COALESCE((SELECT id FROM menus WHERE path = '/tools' LIMIT 1), 0), 6, 1, 0, 'system:webhook:list', NOW(), NOW()
WHERE NOT EXISTS (SELECT 1 FROM menus WHERE path = '/system/webhooks');

-- +goose Down
DELETE FROM menus WHERE path = '/system/webhooks';
DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code LIKE 'system:webhook:%');
DELETE FROM permissions WHERE code LIKE 'system:webhook:%';
DROP TABLE IF EXISTS audit_svc.webhook_cursors;
DROP TABLE IF EXISTS audit_svc.webhook_deliveries;
DROP TABLE IF EXISTS audit_svc.webhook_subscriptions;
