-- +goose Up
ALTER TABLE users
  ADD COLUMN password_changed_at timestamptz(3) DEFAULT NULL;

UPDATE users
SET password_changed_at = created_at
WHERE password_changed_at IS NULL
  AND created_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS password_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NOT NULL,
  password_hash varchar(255) NOT NULL,
  changed_at timestamptz(3) NOT NULL,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_password_history_user_id ON password_history (user_id);
CREATE INDEX IF NOT EXISTS idx_password_history_user_changed ON password_history (user_id, changed_at);

-- +goose Down
DROP TABLE IF EXISTS password_history;

ALTER TABLE users
  DROP COLUMN password_changed_at;
