import {
  ApiOutlined,
  AudioOutlined,
  AuditOutlined,
  CheckSquareOutlined,
  SendOutlined,
  ControlOutlined,
  ForkOutlined,
  SoundOutlined,
  StopOutlined,
  DashboardOutlined,
  UserOutlined,
  TeamOutlined,
  SafetyOutlined,
  MenuOutlined,
  ApartmentOutlined,
  DatabaseOutlined,
  FileOutlined,
  LoginOutlined,
  FileTextOutlined,
  NotificationOutlined,
  SettingOutlined,
  CodeOutlined,
  MonitorOutlined,
  CloudServerOutlined,
  ScheduleOutlined,
  BarsOutlined,
  SearchOutlined,
  AimOutlined,
  IdcardOutlined,
  ThunderboltOutlined,
  WarningOutlined,
  ToolOutlined,
  BookOutlined,
  GlobalOutlined,
  PhoneOutlined,
  FundOutlined,
  RadarChartOutlined,
  VideoCameraOutlined,
  MailOutlined,
  ClockCircleOutlined,
  BellOutlined,
  BarChartOutlined,
  PayCircleOutlined,
  SafetyCertificateOutlined,
  DesktopOutlined,
  AppstoreOutlined,
  EditOutlined,
  ShareAltOutlined,
} from '@ant-design/icons'

export interface MenuDef {
  label: string
  key: string
  icon: React.ReactNode
  perm?: string
  children?: MenuDef[]
}

// 后端菜单 icon 字段（字符串）→ antd 图标
const ICON_MAP: Record<string, React.ReactNode> = {
  dashboard: <DashboardOutlined />,
  setting: <SettingOutlined />,
  user: <UserOutlined />,
  'user-safety': <TeamOutlined />,
  secured: <SafetyOutlined />,
  menu: <MenuOutlined />,
  'root-list': <ApartmentOutlined />,
  file: <FileOutlined />,
  'data-base': <DatabaseOutlined />,
  notification: <NotificationOutlined />,
  'user-list': <MonitorOutlined />,
  time: <ScheduleOutlined />,
  'chart-analytics': <CloudServerOutlined />,
  server: <CloudServerOutlined />,
  data: <BarsOutlined />,
  'user-circle': <UserOutlined />,
  team: <TeamOutlined />,
  book: <BookOutlined />,
  global: <GlobalOutlined />,
  phone: <PhoneOutlined />,
  control: <ControlOutlined />,
  sound: <SoundOutlined />,
  gateway: <ApiOutlined />,
  api: <ApiOutlined />,
  fork: <ForkOutlined />,
  fund: <FundOutlined />,
  queue: <TeamOutlined />,
  audio: <AudioOutlined />,
  stop: <StopOutlined />,
  radar: <RadarChartOutlined />,
  video: <VideoCameraOutlined />,
  mail: <MailOutlined />,
  clock: <ClockCircleOutlined />,
  bell: <BellOutlined />,
  alert: <BellOutlined />,
  chart: <BarChartOutlined />,
  money: <PayCircleOutlined />,
  safety: <SafetyCertificateOutlined />,
  desktop: <DesktopOutlined />,
  edit: <EditOutlined />,
  share: <ShareAltOutlined />,
  audit: <AuditOutlined />,
  check: <CheckSquareOutlined />,
  send: <SendOutlined />,
  appstore: <AppstoreOutlined />,
  aim: <AimOutlined />,
  search: <SearchOutlined />,
  thunderbolt: <ThunderboltOutlined />,
  warning: <WarningOutlined />,
  idcard: <IdcardOutlined />,
  'file-text': <FileTextOutlined />,
  tool: <ToolOutlined />,
  code: <CodeOutlined />,
}

export function iconOf(name?: string): React.ReactNode {
  return (name && ICON_MAP[name]) || <AppstoreOutlined />
}

// 后端菜单为空（未播种/请求失败）时的静态兜底，与路由表保持一致
export const MENU_DEFS: MenuDef[] = [
  { label: '仪表盘', key: '/dashboard', icon: <DashboardOutlined /> },
  // 与 menu_seed.go 的拆组一致：系统管理只留组织+权限，其余拆入 消息中心/日志审计/系统工具。
  // 子菜单 path 不变，分组 key 不再是子路径前缀。
  {
    label: '系统管理',
    key: '/system',
    icon: <SettingOutlined />,
    children: [
      { label: '用户管理', key: '/system/user', icon: <UserOutlined /> },
      { label: '角色管理', key: '/system/role', icon: <TeamOutlined /> },
      { label: '权限管理', key: '/system/permission', icon: <SafetyOutlined /> },
      { label: '菜单管理', key: '/system/menu', icon: <MenuOutlined /> },
      { label: '部门管理', key: '/system/department', icon: <ApartmentOutlined /> },
      { label: '岗位管理', key: '/system/post', icon: <IdcardOutlined /> },
      { label: '租户管理', key: '/system/tenant', icon: <TeamOutlined /> },
      { label: '租户套餐', key: '/system/tenant-packages', icon: <AppstoreOutlined /> },
      { label: '系统设置', key: '/system/setting', icon: <SettingOutlined /> },
    ],
  },
  {
    label: '消息中心',
    key: '/msg',
    icon: <NotificationOutlined />,
    children: [
      { label: '公告管理', key: '/system/notice', icon: <NotificationOutlined /> },
      { label: '短信管理', key: '/system/sms', icon: <MailOutlined /> },
    ],
  },
  {
    label: '日志审计',
    key: '/logs',
    icon: <FileTextOutlined />,
    children: [
      { label: '操作日志', key: '/system/operation-log', icon: <FileTextOutlined /> },
      { label: '登录日志', key: '/system/login-log', icon: <LoginOutlined /> },
      { label: '审计日志', key: '/system/audit-log', icon: <SafetyOutlined /> },
      { label: '在线用户', key: '/system/online-user', icon: <MonitorOutlined /> },
    ],
  },
  {
    label: '系统工具',
    key: '/tools',
    icon: <ToolOutlined />,
    children: [
      { label: '代码生成', key: '/system/codegen', icon: <CodeOutlined /> },
      { label: '字典管理', key: '/system/dict', icon: <DatabaseOutlined /> },
      { label: '文件管理', key: '/system/file', icon: <FileOutlined /> },
      { label: '错误码管理', key: '/system/errcodes', icon: <WarningOutlined /> },
      { label: 'OAuth2 应用', key: '/system/oauth2', icon: <ApiOutlined /> },
      { label: 'Webhook 订阅', key: '/system/webhooks', icon: <ApiOutlined /> },
    ],
  },
  {
    label: '运维监控',
    key: '/monitor',
    icon: <CloudServerOutlined />,
    children: [
      { label: '服务器监控', key: '/monitor/server', icon: <CloudServerOutlined /> },
      { label: '数据库监控', key: '/monitor/mysql', icon: <DatabaseOutlined /> },
      { label: 'Redis 监控', key: '/monitor/redis', icon: <BarsOutlined /> },
      { label: '定时任务', key: '/monitor/job', icon: <ScheduleOutlined /> },
      { label: '告警规则', key: '/monitor/alerts', icon: <BellOutlined /> },
    ],
  },
  {
    label: '审批中心',
    key: '/bpm',
    icon: <AuditOutlined />,
    children: [
      { label: '待办中心', key: '/bpm/tasks', icon: <CheckSquareOutlined /> },
      { label: '我发起的', key: '/bpm/instances', icon: <SendOutlined /> },
      { label: '流程定义', key: '/bpm/definitions', icon: <ForkOutlined /> },
    ],
  },
]


export const pathBreadcrumbMap: Record<string, string> = {
  '/dashboard': '仪表盘',
  '/profile': '个人中心',
  '/system/user': '用户管理',
  '/system/role': '角色管理',
  '/system/permission': '权限管理',
  '/system/menu': '菜单管理',
  '/system/department': '部门管理',
  '/system/dict': '字典管理',
  '/system/file': '文件管理',
  '/system/notice': '公告管理',
  '/system/login-log': '登录日志',
  '/system/operation-log': '操作日志',
  '/system/audit-log': '审计日志',
  '/system/online-user': '在线用户',
  '/system/setting': '系统设置',
  '/system/tenant': '租户管理',
  '/system/codegen': '代码生成',
  '/system/sms': '短信管理',
  '/system/oauth2': 'OAuth2 应用',
  '/system/errcodes': '错误码管理',
  '/system/post': '岗位管理',
  '/system/tenant-packages': '租户套餐',
  '/monitor/server': '服务器监控',
  '/monitor/mysql': '数据库监控',
  '/monitor/redis': 'Redis 监控',
  '/monitor/job': '定时任务',
  '/monitor/alerts': '告警规则',
  '/bpm/tasks': '待办中心',
  '/bpm/instances': '我发起的',
  '/bpm/definitions': '流程定义',
}

// 分组 key（含前导 /）→ 面包屑上的分组名和图标
export const GROUP_META: Record<string, { label: string; icon: React.ReactNode }> = {
  '/system': { label: '系统管理', icon: <SettingOutlined /> },
  '/msg': { label: '消息中心', icon: <NotificationOutlined /> },
  '/logs': { label: '日志审计', icon: <FileTextOutlined /> },
  '/tools': { label: '系统工具', icon: <ToolOutlined /> },
  '/monitor': { label: '运维监控', icon: <CloudServerOutlined /> },
  '/bpm': { label: '审批中心', icon: <AuditOutlined /> },
}

